"""core initial schema

Revision ID: 9cfe52a7cfff
Revises:
Create Date: 2026-04-22 14:24:30.200885

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
# ``branch_labels = ("core",)`` so downstream migration chains (in a separate
# repo, under their own version-locations) can set ``depends_on = "core@head"``
# without pinning a specific revision hash.
revision: str = "9cfe52a7cfff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("core",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alembic_version_cloud")
    op.drop_index(op.f("ix_cloud_subscriptions_org_id"), table_name="cloud_subscriptions")
    op.drop_index(
        op.f("ix_cloud_subscriptions_polar_customer_id"), table_name="cloud_subscriptions"
    )
    op.drop_table("cloud_subscriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_subscriptions",
        sa.Column("org_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "polar_subscription_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("polar_customer_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("polar_product_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column(
            "granted_benefits",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "current_period_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "current_period_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "canceled_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
            name=op.f("cloud_subscriptions_org_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cloud_subscriptions_pkey")),
        sa.UniqueConstraint(
            "polar_subscription_id",
            name=op.f("cloud_subscriptions_polar_subscription_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_cloud_subscriptions_polar_customer_id"),
        "cloud_subscriptions",
        ["polar_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cloud_subscriptions_org_id"), "cloud_subscriptions", ["org_id"], unique=False
    )
    op.create_table(
        "alembic_version_cloud",
        sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_cloud_pkc")),
    )
    # ### end Alembic commands ###
