"""Emit a TOML file with every config key + its default value.

Operators run ``just config-dump > nagara.toml`` to get a starting template
for ``~/.config/nagara/config.toml`` or ``[tool.nagara]`` in pyproject.toml.
Secrets are masked as ``"***"`` — the dumped file is safe to commit.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running this as ``python scripts/config-dump.py`` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from nagara.config import Settings  # noqa: E402
from nagara.profiles import _toml_value  # noqa: E402


def main() -> None:
    settings = Settings()
    data = settings.safe_dump(include_secrets=False)

    lines = ["# Generated by scripts/config-dump.py — edit as needed.", "[tool.nagara]", ""]
    for key, value in sorted(data.items()):
        if value is None:
            # No sensible TOML scalar for None — comment the key so the shape
            # stays discoverable but the file is a valid starting point.
            lines.append(f"# {key} =")
            continue
        # StrEnum / Enum → use the .value so it round-trips cleanly.
        if hasattr(value, "value") and not isinstance(value, bool):
            value = value.value
        try:
            rendered = _toml_value(value)
        except TypeError:
            # Fall back to string for types our mini-writer doesn't know
            # (e.g. timedelta). Operators can tweak manually.
            rendered = _toml_value(str(value))
        lines.append(f"{key} = {rendered}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
