"""Render ``docs/config-reference.md`` from :class:`Settings.model_fields`.

Runs on every release (and locally via ``just config-docs``). Keeps the
reference in sync with the actual pydantic model so it can't drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from the repo root.
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))

from pydantic.fields import FieldInfo  # noqa: E402

from nagara.config import Settings  # noqa: E402

OUTPUT = _ROOT / "docs" / "config-reference.md"


def _format_type(field: FieldInfo) -> str:
    """Render a readable type string. pydantic's ``annotation`` may be a
    fancy construct (Literal, Optional, generic, …); stringify and clean."""
    ann = field.annotation
    if ann is None:
        return "—"
    s = str(ann)
    s = s.replace("typing.", "")
    for prefix in ("nagara.config.", "pydantic.types.", "builtins."):
        s = s.replace(prefix, "")
    if s.startswith("<class '") and s.endswith("'>"):
        s = s[len("<class '") : -len("'>")]
    # Escape pipe characters so they don't break the Markdown table layout.
    s = s.replace("|", "\\|")
    return s


def _format_default(field: FieldInfo) -> str:
    """Readable default value. Empty string / None → ``—`` so the table
    stays legible."""
    from typing import Any, cast

    factory = cast(Any, field.default_factory)
    if factory is not None:
        # pydantic supports zero-arg and data-arg factories; try both.
        try:
            default = factory()
        except TypeError:
            try:
                default = factory({})
            except TypeError:
                return "computed"
    else:
        default = field.default
    if default is None or default == "":
        return "—"
    # StrEnum → show the .value instead of the repr shape.
    if hasattr(default, "value") and not isinstance(default, bool):
        return f"`{default.value!r}`"
    # SecretStr renders as '**********' — safe for public docs.
    return f"`{default!r}`"


def _format_constraints(field: FieldInfo) -> str:
    """Extract numeric / string bounds from Field() metadata."""
    parts: list[str] = []
    for m in field.metadata:
        name = type(m).__name__
        if name == "Ge":
            parts.append(f"≥ {m.ge}")
        elif name == "Gt":
            parts.append(f"> {m.gt}")
        elif name == "Le":
            parts.append(f"≤ {m.le}")
        elif name == "Lt":
            parts.append(f"< {m.lt}")
        elif name == "MinLen":
            parts.append(f"min len {m.min_length}")
        elif name == "MaxLen":
            parts.append(f"max len {m.max_length}")
    return ", ".join(parts) or "—"


def render() -> str:
    lines = [
        "# Config reference",
        "",
        "Generated by `scripts/generate-config-docs.py` — do not edit by hand.",
        "",
        "Every key here is readable via the `NAGARA_*` env vars, from a ",
        "`[tool.nagara]` table in `pyproject.toml`, from `~/.config/nagara/",
        "config.toml`, or from a named profile in `~/.config/nagara/profiles.toml`.",
        "See [development.md](./development.md) for the full priority order.",
        "",
        "| Name | Type | Default | Constraints | Description |",
        "|------|------|---------|-------------|-------------|",
    ]
    for name, field in Settings.model_fields.items():
        description = (field.description or "").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| `{name}` | `{_format_type(field)}` | {_format_default(field)} | "
            f"{_format_constraints(field)} | {description} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
